apiVersion: v1
kind: PersistentVolume
metadata:
  name: task1-pv-local
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Mi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /data/task1-pv-local