---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task2-deployment
  namespace: lesson7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task2-deployment
  template:
    metadata:
      labels:
        app: task2-deployment
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - mountPath: /exchange
          name: exchange
      volumes:
      - name: exchange
        persistentVolumeClaim:
          claimName: task2-nfs-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task2-nfs-pvc
  namespace: lesson7
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Mi
