---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task1-deployment
  namespace: lesson6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task1
  template:
    metadata:
      labels:
        app: task1
    spec:
      containers:
      - name: busybox
        image: busybox:1.36.1
        command: ['sh', '-c', "while true; do echo write something at $(date) >> /out/messages.log; sleep 5; done"]
        volumeMounts:
        - mountPath: /out
          name: messages
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - mountPath: /in
          name: messages
      volumes:
      - name: messages
        emptyDir:
          sizeLimit: 100Mi
